### ISSUE TITLE
Does not work, always returns "None" instead of "Pass"

### ISSUE THREAD

**Issue by niftylettuce** [mediamonks/node-spf-check#3]
You should probably write tests for this

**Comment by jm42** [comment]
Need more information.

See [here](https://github.com/mediamonks/node-spf-check/blob/master/spec/indexSpec.js#L202) for test that always returns "Pass" instead of "None".

**Comment by jm42** [comment]
Hello @niftylettuce. Can you provide more information about what does not work? Thanks.

**Comment by jm42** [comment]
Closing because lack of information. Feel free to open a new issue.
